version: '3.3'

services:
  imoutopics:
    restart: always
    image: imoutochan/imoutopics:latest
    networks:
      - customnetwork
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "42427:80"
    volumes:
      - ./idata:/app/idata
      

networks:
  customnetwork:
     driver: bridge
